---
- name: install docker
  import_tasks: install_docker.yaml
  tags: install_docker
  when: ansible_os_family == "Debian"

- name: config docker
  import_tasks: config_docker.yaml
  tags: config_docker
  when: ansible_os_family == "Debian"
