---
- name: Create a sub.observability.archidev.ir A record to point to host
  community.general.cloudflare_dns:
    zone: "{{domain}}"
    record: "{{item}}.{{inventory_hostname}}"
    type: A
    value: "{{ansible_host}}"
    account_email: "{{ACCOUNT_EMAIL}}"
    account_api_key: "{{ACCOUNT_API_KEY}}"
    state: present 
  loop: "{{sublist}}"