---
- name: copy compose files into host
  import_tasks: copy.yaml
  tags: copy_compose

- name: set dns record
  import_tasks: dnsrecord.yaml
  tags: set_dns

- name: run docker compose file
  import_tasks: compose_ansible.yaml
  tags: run_compose


