global:
  scrape_interval:     30s
  evaluation_interval: 30s
  external_labels:
      monitor: 'prom'

rule_files:
  - '/etc/prometheus/alerts/*.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
        - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'https-cadvisor'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets:
      - cad.obs.archidev.ir
      - cad.git.archidev.ir
      - cad.gitlab-runner.archidev.ir
      - cad.production.archidev.ir
      - cad.pre-product.archidev.ir
      - cad.bitmail.archidev.ir
      - cad.postgres.archidev.ir
      - cad.redis.archidev.ir
      - cad.minio.archidev.ir
      - cad.awx.archidev.ir
    basic_auth:
      username: 'sina'
      password: 'sina.neissi'

  - job_name: 'https-node-exporter'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
    - targets:
      - nod.obs.archidev.ir
      - nod.git.archidev.ir
      - nod.gitlab-runner.archidev.ir
      - nod.production.archidev.ir
      - nod.pre-product.archidev.ir
      - nod.bitmail.archidev.ir
      - nod.postgres.archidev.ir
      - nod.redis.archidev.ir
      - nod.minio.archidev.ir
      - nod.awx.archidev.ir
    basic_auth:
      username: 'sina'
      password: 'sina.neissi'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'blackbox-web'
    metrics_path: '/probe'
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['https://DockerMe.ir', 'https://Google.com', 'https://www.arvancloud.com']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - target_label: region
        replacement: "local"

  - job_name: 'blackbox-ping'
    scrape_interval: 30s
    metrics_path: /probe
    params:
      module: [icmp_ipv4]
    static_configs:
      - targets: ['8.8.8.8', 'google.com']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'grafana'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'alertmanager'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'pushgateway'
    scrape_interval: 30s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8082']
